/**********************************************************************************************
    * @Author:      Tirthankar - Salesforce COE 
    * @Date:        24th June 2020
    * @Description: class to store the hard coded value.
    ***********************************************************************************************/
    public with sharing class ApplicationConstant {
        public static final String ACCOUNT_TRIGGER_HANDLER_NAME = 'AccountTriggerHandler';
        public static final String APEX = 'Apex';
        public static final String FLOW = 'Flow';
        public static final String BATCHAPEX = 'Batch Apex';
        public static final String NUMBER_OF_SOQL = 'Number of SOQL queries: ';
        public static final String NUMBER_OF_QUERYROWS = 'Number of query rows: ';
        public static final String NUMBER_OF_SOSL = 'Number of SOSL queries: ';
        public static final String NUMBER_OF_DML = 'Number of DML rows: ';
        public static final String NUMBER_OF_DMLSTATEMENTS = 'Number of DML statements: ';
        public static final String MAXIMUM_CPU_TIME = 'Maximum CPU time: ';
        public static final String MAXIMUM_HEAP_SIZE = 'Maximum heap size: ';
        public static final String NUMBER_OF_FUTURE_CALLS = 'Number of future calls: ';
        public static final String NUMBER_OF_CALLOUTS = 'Number of callouts: ';
        public static final String NUMBER_OF_QUEUABLE = 'Number of queueable jobs added to the queue: ';
        public static final String NEXTLINE = '\n';
        public static final String SLASH = '/';
        public static final String DMLEXCEPTION  = 'System.DmlException';
        public static final String RETRYERROR = 'Condition is not met, so retrying the trigger again';
        public static final String CUSTOM_METADATA_NAME  = 'Error_Config';
        /*public static final String BATCH_APEXTRIGGERHANDLER  = 'BatchApexErrorEventTrigger';
        public static final String FLOW_EXECUTION_TRIGGERHANDLER  = 'FlowExecutionErrorEventTrigger';
        public static final String BATCH_APEX_ERROR_EVENT  = 'BatchApexErrorEvent';
        public static final String FLOW_EXECUTION_ERROR_EVENT  = 'FlowExecutionErrorEvent';
        public static final String REST_API_URL  = '/services/data/v47.0/sobjects/ApexTrigger';
        public static final String POST  = 'POST';
        public static final String CONTENT_TYPE  = 'Content-Type';
        public static final String APPLICATION_JSON  = 'application/json';
        public static final String AUTHORIZATION  = 'Authorization';
        public static final String BEARER  = 'Bearer ';
        public static final String BATCHAPEXTRIGGERHANDLERMETHOD  = 'Logforce.BatchApexErrorEventTriggerHandler.afterInsert(Trigger.new);';
        public static final String FLOWEXECUTIONTRIGGERHANDLERMETHOD  = 'Logforce.FlowExecutionEventTriggerHandler.afterInsert(Trigger.new);';
        public static final String JSON1  = '{"Name" : "';
        public static final String JSON2  = '",';
        public static final String JSON3  = '"TableEnumOrId" : "';
        public static final String JSON4  = '"Body" : "trigger ';
        public static final String JSON5  = ' on ';
        public static final String JSON6  = ' (after insert)\\n{\\n';
        public static final String JSON7  = '\\t';
        public static final String JSON8  = '\\n';
        public static final String JSON9  = '}"';
        public static final String JSON10  = '}';*/
        public static final String COMMA = ',';
        public static final String SPACE = '';
        
    }